package repository;

import model.AddressUser;
import model.User;
import util.PostgreSQLConnect;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Logger;

public class WorkWithTables {
    private static Logger logger = Logger.getLogger("util.WorkWithTables");

    public void createTable(){
        try (Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword())) {
            PreparedStatement preparedStatement = connection.prepareStatement("CREATE TABLE users" +
                    "(usersId int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                    "first_name  VARCHAR,\n" +
                    "last_name VARCHAR,\n" +
                    "age INTEGER) ");
            preparedStatement.executeUpdate();
            logger.info("Таблица созданна.");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void addTable(User user){
        try (Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword())) {
            PreparedStatement preparedStatement = connection.prepareStatement("INSERT INTO users (first_name, last_name, age) VALUES (?, ?, ?);");
            preparedStatement.setString(1, user.getFirstName());
            preparedStatement.setString(2, user.getLastName());
            preparedStatement.setInt(3, user.getAge());
            preparedStatement.executeUpdate();
            logger.info("Пользователь " + user + " внесен в базу данных.");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void deleteUser(int number) {
        try {
            Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword());
            PreparedStatement preparedStatement = connection.prepareStatement("DELETE FROM users WHERE usersId = ?");
            preparedStatement.setInt(1, number);
            preparedStatement.executeUpdate();
            logger.info("Пользователь "  + " удален из базы данных");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public  void viewAllUsers(){
        try {
            Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword());
            PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM users");
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()){
                int id = resultSet.getInt("id");
                int age = resultSet.getInt("age");
                String first = resultSet.getString("first_name");
                String last = resultSet.getString("last_name");

                System.out.print("id: " + id);
                System.out.print(", firstName: " + first);
                System.out.print(", lastName: " + last);
                System.out.println(", age: " + age);
            }
            logger.info("Показанны все пользователи базы данных.");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
    public void selectUserById(int number){
        try{
            Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword());
            PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM users WHERE usersId = ?");
            preparedStatement.setInt(1, number);
            ResultSet resultSet = preparedStatement.executeQuery();
            while(resultSet.next()) {
                int id = resultSet.getInt("id");
                int age = resultSet.getInt("age");
                String first = resultSet.getString("first_name");
                String last = resultSet.getString("last_name");

                System.out.print("id: " + id);
                System.out.print(", firstName: " + first);
                System.out.print(", lastName: " + last);
                System.out.println(", age: " + age);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void updateUser(int number){

        try{
            Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword());
            String updateUsers = "UPDATE users SET age =  30  WHERE usersId = ?";
            PreparedStatement preparedStatement = connection.prepareStatement(updateUsers);
            preparedStatement.setInt(1, number);
            int count = preparedStatement.executeUpdate();
            System.out.println("Внесено " + count + " изменений в табллицу данных");
            preparedStatement.close();
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

     public void deleteAllUsers(){
        try {
             Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword());
             PreparedStatement preparedStatement = connection.prepareStatement("DELETE FROM users");
             int count = preparedStatement.executeUpdate();
             System.out.println("Удалена " + count + " строки из табллицы данных");
             preparedStatement.close();
        } catch (SQLException e) {
             throw new RuntimeException(e);
        }
    }

    public void createTableAddress(){
        try (Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword())) {
            PreparedStatement preparedStatement = connection.prepareStatement("CREATE TABLE users_address" +
                    "(usersId int PRIMARY KEY REFERENCES users(usersId) ON DELETE CASCADE,\n" +
                    "city  VARCHAR,\n" +
                    "street VARCHAR,\n" +
                    "house integer)");
            preparedStatement.executeUpdate();
            logger.info("Таблица созданна.");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void addTableAddress(AddressUser user){
        try (Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword())) {
            PreparedStatement preparedStatement = connection.prepareStatement("INSERT INTO users_address (usersId, city, street, house) VALUES (?, ?, ?, ?)");
            preparedStatement.setInt(1, user.getId());
            preparedStatement.setString(2, user.getCity());
            preparedStatement.setString(3, user.getStreet());
            preparedStatement.setInt(4, user.getHouse());
            preparedStatement.executeUpdate();
            logger.info("Пользователь " + user + " внесен в базу данных.");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void selectUserHouse(int number){
        try{
            Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword());
            PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM users_address WHERE house = ?");
            preparedStatement.setInt(1, number);
            ResultSet resultSet = preparedStatement.executeQuery();
            while(resultSet.next()) {
                int id = resultSet.getInt("usersId");
                String city = resultSet.getString("city");
                String street = resultSet.getString("street");
                int house = resultSet.getInt("house");

                System.out.print("id: " + id);
                System.out.print(", city: " + city);
                System.out.print(", street: " + street);
                System.out.println(", house: " + house);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    public void deleteAllUsers22(){
        try {
            Connection connection = DriverManager.getConnection(PostgreSQLConnect.getUrl(), PostgreSQLConnect.getUsername(), PostgreSQLConnect.getPassword());
            PreparedStatement preparedStatement = connection.prepareStatement("SELECT * FROM users JOIN users_address ON users.usersId = users_address.usersId");
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()){
                int id = resultSet.getInt("usersId");
                String firstName = resultSet.getString("first_name");
                String lastName = resultSet.getString("last_name");
                int age = resultSet.getInt("age");
                String city = resultSet.getString("city");
                String street = resultSet.getString("street");
                int house = resultSet.getInt("house");

                System.out.print("id: " + id);
                System.out.print(", firstName: " + firstName);
                System.out.print(", lastName: " + lastName);
                System.out.print(", age: " + age);
                System.out.print(", city: " + city);
                System.out.print(", street: " + street);
                System.out.println(", house: " + house);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
}
